OBJS = ast.cmo parser.cmo scanner.cmo compile.cmo semantic.cmo bytecode.cmo execute.cmo MDraw.cmo 

TARFILES = Makefile scanner.mll parser.mly ast.ml bytecode.ml interpret.ml compile.ml execute.ml MDraw.ml 

MDraw : $(OBJS)
	ocamlc -o MDraw $(OBJS)
	
scanner.ml : scanner.mll
	ocamllex scanner.mll

parser.ml parser.mli : parser.mly
	ocamlyacc parser.mly

%.cmo : %.ml
	ocamlc -c $<

%.cmi : %.mli
	ocamlc -c $<

MDraw.tar.gz : $(TARFILES)
	cd .. && tar czf MDraw/MDraw.tar.gz $(TARFILES:%=MDraw/%)

.PHONY : clean
clean :
	rm -f MDraw parser.ml parser.mli scanner.ml *.cmo *.cmi *.out *.diff

# Generated by ocamldep *.ml *.mli
ast.cmo: 
ast.cmx: 
bytecode.cmo: ast.cmo 
bytecode.cmx: ast.cmx 
compile.cmo: bytecode.cmo ast.cmo 
compile.cmx: bytecode.cmx ast.cmx 
execute.cmo: bytecode.cmo ast.cmo 
execute.cmx: bytecode.cmx ast.cmx 
interpret.cmo: ast.cmo 
interpret.cmx: ast.cmx 
MDraw.cmo: scanner.cmo parser.cmi interpret.cmo execute.cmo compile.cmo \
	bytecode.cmo ast.cmo 
MDraw.cmx: scanner.cmx parser.cmx interpret.cmx execute.cmx compile.cmx \
    bytecode.cmx ast.cmx 
parser.cmo: ast.cmo parser.cmi 
parser.cmx: ast.cmx parser.cmi 
scanner.cmo: parser.cmi 
scanner.cmx: parser.cmx 
parser.cmi: ast.cmo